name: Development tests
on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    #eslint:
    #    name: eslint
    #   runs-on: ubuntu-latest
    #    steps:
    #        - uses: actions/checkout@v2
    #        - name: Use Node.js 18.12.1
    #          uses: actions/setup-node@v2
    #          with:
    #              node-version: 18.12.1
    #        - run: npm i
    #        - run: npm run lint
    prettier:
        name: prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.12.1
              uses: actions/setup-node@v2
              with:
                  node-version: 18.12.1
            - run: npm i
            - run: npm run format

    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.12.1
              uses: actions/setup-node@v2
              with:
                  node-version: 18.12.1
            - run: npm i
            - run: npm run build
